// <auto-generated />
namespace CodeFirstDatabaseApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201304240919377_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
